# Configuration Render optimisée pour le questionnaire EORTC QLQ-C30
services:
  - type: web
    name: questionnaire-eortc-flask
    env: python
    pythonVersion: "3.11.9"
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements_flask.txt
    startCommand: python app_flask.py
    envVars:
      - key: SECRET_KEY
        value: questionnaire-eortc-2025-secret-key-production-very-secure
      - key: FLASK_DEBUG
        value: False
      - key: AUDIO_ENABLED
        value: True
      - key: USE_GEMINI_TTS
        value: False
      - key: USE_PRO_MODEL
        value: False
      - key: GOOGLE_CLOUD_API_KEY
        value: ""
    healthCheckPath: /api/health
    autoDeploy: true