# Configuration Render optimisée pour le questionnaire EORTC QLQ-C30
services:
  - type: web
    name: questionnaire-eortc-flask
    env: python
    pythonVersion: "3.11.9"
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements_flask.txt
    startCommand: python app_flask.py
    envVars:
      - key: SECRET_KEY
        value: 0RE4oaorR674&%23wQqq0E!pPP8QO6N8KaNXeIK7xb3VLiiPMS9JaRZY502yAAaw
      - key: FLASK_ENV
        value: production
      - key: AUDIO_ENABLED
        value: True
      - key: USE_GEMINI_TTS
        value: False
      - key: USE_PRO_MODEL
        value: False
      - key: GOOGLE_CLOUD_API_KEY
        value: ""
    healthCheckPath: /api/health
    autoDeploy: true